[General]
Threads     = 100

[Log]
Level       = 'INFO'
File        = '/home/yzbsj/文档/Code/pycharm/FVCOM_processing/output/log/log'

[FVCOMOutputDirectory]
Directory   = '/home/yzbsj/文档/FVCOM_lag/INPDIR/2025'

[Lagrangian]

[Lagrangian.General]
Inverse     = true
SourcePath  = '/home/yzbsj/Downloads/Source code of Floating Macroalgal Growth and Drift Model (FMGDM_v1.0)/LAG_source_prolifera_wind_nutrients/'
Directory   = '/home/yzbsj/Documents/FVCOM_lag'
CaseName    = 'tst_new'
Wind        = true
Dragc       = 0.012
ROTATE_ANGLE= 0.000
[Lagrangian.TimeIntegration]
DTI         = 30.0
INSTP       = 600
DTOUT       = 1.0
TDRIFT      = 281
[Lagrangian.StartTime]
YEARLAG     = 2025
MONTHLAG    = 4
DAYLAG      = 3
HOURLAG     = 23
[Lagrangian.IOLocation]
INPDIR      = 'INPDIR'
GEOAREA     = 'subei'
OUTDIR      = 'OUTDIR'
INFOFILE    = 'screen'
LAGINI      = 'particle'
[Lagrangian.Coor]
F_DEPTH     = true
P_SIGMA     = false
OUTSIGMA    = false
[Lagrangian.RandomWalk]
IRW         = 0
DHOR        = 20.0
DTRW        = 1.0
[Lagrangian.ProjectionControl]
CART_SHP    = false
PROJECTION_REFERENCE    = '+proj=longlat +datum=WGS84 +no_defs'